#!/bin/bash
ml load matlab
echo "MINTS Init ;)"
matlab -nodesktop -nodisplay -nosplash -r "addpath('functions','YAMLMatlab_0.4.3') ; livePlotter('1','mintsDefinitions.yaml');quit"
matlab -nodesktop -nodisplay -nosplash -r "addpath('functions','YAMLMatlab_0.4.3') ; livePlotter('2','mintsDefinitions.yaml');quit"
matlab -nodesktop -nodisplay -nosplash -r "addpath('functions','YAMLMatlab_0.4.3') ; livePlotter('3','mintsDefinitions.yaml');quit"
matlab -nodesktop -nodisplay -nosplash -r "addpath('functions','YAMLMatlab_0.4.3') ; livePlotter('4','mintsDefinitions.yaml');quit"
matlab -nodesktop -nodisplay -nosplash -r "addpath('functions','YAMLMatlab_0.4.3') ; livePlotter('5','mintsDefinitions.yaml');quit"
matlab -nodesktop -nodisplay -nosplash -r "addpath('functions','YAMLMatlab_0.4.3') ; livePlotter('6','mintsDefinitions.yaml');quit"
matlab -nodesktop -nodisplay -nosplash -r "addpath('functions','YAMLMatlab_0.4.3') ; livePlotter('7','mintsDefinitions.yaml');quit"
matlab -nodesktop -nodisplay -nosplash -r "addpath('functions','YAMLMatlab_0.4.3') ; livePlotter('8','mintsDefinitions.yaml');quit"
matlab -nodesktop -nodisplay -nosplash -r "addpath('functions','YAMLMatlab_0.4.3') ; livePlotter('9','mintsDefinitions.yaml');quit"
matlab -nodesktop -nodisplay -nosplash -r "addpath('functions','YAMLMatlab_0.4.3') ; livePlotter('10','mintsDefinitions.yaml');quit"
matlab -nodesktop -nodisplay -nosplash -r "addpath('functions','YAMLMatlab_0.4.3') ; livePlotter('11','mintsDefinitions.yaml');quit"
matlab -nodesktop -nodisplay -nosplash -r "addpath('functions','YAMLMatlab_0.4.3') ; livePlotter('12','mintsDefinitions.yaml');quit"
matlab -nodesktop -nodisplay -nosplash -r "addpath('functions','YAMLMatlab_0.4.3') ; livePlotter('13','mintsDefinitions.yaml');quit"
matlab -nodesktop -nodisplay -nosplash -r "addpath('functions','YAMLMatlab_0.4.3') ; livePlotter('14','mintsDefinitions.yaml');quit"
matlab -nodesktop -nodisplay -nosplash -r "addpath('functions','YAMLMatlab_0.4.3') ; livePlotter('15','mintsDefinitions.yaml');quit"
echo "MINTS Done :)"
#matlab -nodesktop -nodisplay -nosplash -r "addpath('functions','YAMLMatlab_0.4.3') ; liveRunDynamicM('16','mintsDefinitions.yaml');quit"
#matlab -nodesktop -nodisplay -nosplash -r "addpath('functions','YAMLMatlab_0.4.3') ; liveRunDynamicM('17','mintsDefinitions.yaml');quit"
#matlab -nodesktop -nodisplay -nosplash -r "addpath('functions','YAMLMatlab_0.4.3') ; liveRunDynamicM('18','mintsDefinitions.yaml');quit"
#matlab -nodesktop -nodisplay -nosplash -r "addpath('functions','YAMLMatlab_0.4.3') ; liveRunDynamicM('19','mintsDefinitions.yaml');quit"

